<?php

namespace Code\Bundle\ChallengeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BuildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildRepository extends EntityRepository
{
    public function getBuilds() {
        $query = $this->createQueryBuilder('b')
            ->orderBy('b.id', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
