<?php

namespace Code\Bundle\ChallengeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeveloperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeveloperRepository extends EntityRepository
{
    /**
     * Return order list of Developers
     *
     * @return array
     */
    public function getDevelopers() {
        $query = $this->createQueryBuilder('d')
            ->orderBy('d.name', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
