<?php

namespace Code\Bundle\ChallengeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedRepository extends EntityRepository
{
    /**
     * Latest facebook feeds
     *
     * @return array
     */
    public function getLatestFeeds() {
        $query = $this->createQueryBuilder('f')
            ->orderBy('f.created_date', 'DESC')
            ->getQuery();

        return $query->getResult();
    }
}
