parameters:
#    code_challenge.example.class: Code\Bundle\ChallengeBundle\Example

services:
#    code_challenge.example:
#        class: %code_challenge.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
